<?php

namespace app\admin\controller;

use think\Controller;
use think\Request;
use think\Session;

class BaseController extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->checkLogin();
    }

    /**
     * 确认后台管理员登录页面
     */
    public function checkLogin()
    {
        if (Session::get('adminAccount')["id"] == null)//获取session中存储的值
        {   //如果没有的话跳转回登录页面
            $this->error("请先登录，别做一些越权行为，这是不好的; 如果不是管理员请绕道",url('login/index'));
        }
    }


    public function status(Request $request)
    {
        /* 需要验证的话可添加 */
        $data = $request->param();
        if(empty($data["id"]))
        {
            $this->error("ID不合法！！");
        }
        if(!is_numeric($data["status"]))
        {
            $this->error("状态不合法！！");
        }

        //使用ThinkPHP的request对象获取当前调用的类名
        $res = model($request->controller())->update(["status" => $data["status"]], ["id" => $data["id"]]);

        if ($res) {
            $this->success("状态修改成功");
        } else {
            $this->error("状态修改失败");
        }
    }
}