<?php

namespace app\admin\controller;

use think\Controller;
use think\Request;

class Bis extends Controller
{
    private $bisModel;
    private $bisLocationModel;
    private $bisAccountModel;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->bisModel = model("Bis");
        $this->bisLocationModel = model("BisLocation");
        $this->bisAccountModel = model("BisAccount");
    }

    public function index()
    {
        return $this->fetch();
    }

    /**
     * 展示审核入驻申请的商家列表页面
     */
    public function apply()
    {
        $bisData = $this->bisModel->getBisByStatus();
        //print_r($bisData);exit;
        $this->assign("bisData", $bisData);
        return $this->fetch();
    }

    /**
     * 展示审核入驻申请的商家详情页面
     */
    public function detail(Request $request)
    {
        $bisId =  $request->param("bisId");
        //echo $bisId; exit;

        //获取商户基本信息并传递给模板
        $bisData = $this->bisModel->find($bisId);
        //print_r($bisData);
        $this->assign("bisData", $bisData);

        //获取商户总店信息并传递给模板
        $bisLocationData = $this->bisLocationModel->getBisLocationByBisId($bisId);
        //print_r($bisLocationData);exit;
        $this->assign("bisLocationData", $bisLocationData);

        //获取商户账户信息并传递给模板
        $bisAccountData = $this->bisAccountModel->getBisAccountByBisId($bisId);
        //print_r($bisAccountData);exit;
        $this->assign("bisAccountData", $bisAccountData);


        return $this->fetch();
    }

    /**
     * 展示删除入驻商家页面
     */
    public function dellist()
    {
        return $this->fetch();
    }
}