<?php

namespace app\admin\controller;

use think\Request;

class Featured extends BaseController
{
    private $featuredModel;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->featuredModel = model("Featured");
    }

    public function index(Request $request)
    {
        //获取推荐位类别
        $types = config("featured.featured_type");
        $this->assign("types", $types);

        $type = 0;
        if($request->isPost())
        {
            $type = $request->post("type");
        }
        $this->assign("type",$type);

        $featuredData = $this->featuredModel->getFeaturedsByType($type);
        $this->assign("featuredData",$featuredData);

        return $this->fetch();
    }

    public function add(Request $request)
    {
        //获取推荐位类别
        $types = config("featured.featured_type");
        $this->assign("types", $types);

        if($request->isPost())
        {
            $data = $request->post();

            //验证数据
            $validate = validate("Featured");
            if(!$validate->check($data)) {
                $this->error($validate->getError());
            }

            $data["status"] = 0;

            $id = $this->featuredModel->add($data);
            if($id) {
                $this->success("添加推荐位成功");
            } else {
                $this->error("添加推荐位失败");
            }
        }
        return $this->fetch();
    }
}