<?php

namespace app\bis\controller;

use think\Controller;
use think\Session;

class BaseController extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->checkLogin();
    }


    /**
     * 确认用户登录页面
     */
    public function checkLogin()
    {
        if (Session::get('bisId') == null)//获取session中存储的值
        {   //如果没有的话跳转回登录页面
            $this->error("请先登录，别做一些越权行为，这是不好的",url('login/index'));
        }
    }
}