<?php

namespace app\api\controller;

use think\Controller;
use think\Request;

class City extends Controller
{
    private $cityModel;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->cityModel = model("City");
    }

    public function getCityByParentId(Request $request)
    {
        $cityParentId = $request->post("id");
        //return $cityParentId;//测试是否能够获取Ajax传来的值
        if(!$cityParentId){
            $this->error("城市ID不能为空");
        }

        $secondCityData =  $this->cityModel->getNormalCityByParentID($cityParentId);
        //print_r($secondCityData);

        if(!$secondCityData){
            return ["status" => 0, "message" => "error"];
        }
        return [ "status" => 1, "message" => "success", "data" => $secondCityData];
    }
}